### ISSUE TITLE
Firefox 63: It takes 2 Tab hits to move focus from one checkbox to another

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-checkbox#128]
![vaadin-checkbox](https://user-images.githubusercontent.com/6059356/45543529-60a83980-b81d-11e8-81f0-8de0df06894c.gif)

I checked if it's a `control-state-mixin` issue, but no - it happens only for checkbox.

Firefox 63 beta, Windows

**Comment by web-padawan** [comment]
Confirmed. Note that changing `focusElement` from `label` to `input` fixes that issue.

**Comment by web-padawan** [comment]
vanilla web component reproduction: https://jsfiddle.net/webpadawan/mLekp81o/
