### ISSUE TITLE
checked-changed event fired on page load

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-checkbox#14]
The function is called even though I have not clicked on anything

```
<dom-module id="test-check">

      <template>
        <vaadin-checkbox on-checked-changed="_changeCheck">asd</vaadin-checkbox>
      </template>

      <script>
        class TestCheck extends Polymer.Element {
          static get is() { return 'test-check'; }

          _changeCheck() {
            console.log('Gets fired on page load');
          }
        }

        window.customElements.define(TestCheck.is, TestCheck);
      </script>

    </dom-module>

    <test-check></test-check>
```

**Comment by limonte** [comment]
I can confirm this issue, jsfiddle to quickly reproduce: https://jsfiddle.net/6r5htd05/18/

**Comment by tomivirkki** [comment]
How is this an issue? Any property in Polymer that's marked to `notify` and given a default value will fire a {propertyName}-changed event, right? This is to enable two-way binding and the initial -change event is fired to ensure any host that binds to a property is in sync initially. It's just how Polymer works, not a `<vaadin-checkbox>` issue.

**Comment by web-padawan** [comment]
@tomivirkki I can share some use cases:

1. analysts might want to send event to Google Analytics when checkbox value is changed by user interaction,
2. developers might want to perform AJAX request when checkbox value is changed by user (mostly for non-critical actions, e. g. subscribe / unsubscribe to email newsletter).

BTW, in out team we are using `paper-checkbox` with a 500ms delay for the 2nd case above: if the user taps on checkbox quickly multiple times, state change is being delayed using `debounce` and only after that period elapses, event is being fired. 

This enables us not to perform exclusive AJAX requests, and if the final state is the same as the former one (before multiple clicks) - event isn't fired at all, and thus request not performed.

**Comment by tomivirkki** [comment]
@web-padawan If we want to distinguish user-originated changes, we can have a dedicated event for them (instead of working around Polymer’s binding system events). I think some of our elements already fire a dedicated `change` event for just that purpose.

**Comment by jouni** [comment]
A `change` event would be nice.

**Comment by limonte** [comment]
The `change` event was added and released in https://github.com/vaadin/vaadin-checkbox/releases/tag/v2.1.0

```js
const myCheckbox = document.getElementById('my-checkbox')
  
myCheckbox.addEventListener('change', () => {
  console.log(myCheckbox.checked)
})
```
