### ISSUE TITLE
checked-changed event doesn't have right value

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-checkbox#15]
`checked-changed` event is fired before the `checked` value is actually changed. Similar to: https://github.com/vaadin/vaadin-date-picker/issues/410

**Comment by tomivirkki** [comment]
Can't reproduce anymore. Reopen if still valid.

**Comment by limonte** [comment]
The `change` event was added and released in https://github.com/vaadin/vaadin-checkbox/releases/tag/v2.1.0

```js
const myCheckbox = document.getElementById('my-checkbox')
  
myCheckbox.addEventListener('change', () => {
  console.log(myCheckbox.checked)
})
```
