### ISSUE TITLE
Style changes applied on shadow DOM elements using host attributes do not get repainted on iOS

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-checkbox#16]
The Valo theme for checkbox suffers from the same problem as the Material and Valo themes for vaadin-text-field, that the CSS updates on shadow DOM elements, applied using selectors that target host attributes, do not get repainted by the browser (a Safari bug).

One option is to copy a similar hack as used in vaadin-text-field (I verified this to work for Valo theme): https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L394-L403

A workaround is to toggle some property on the affected elements using the native input element’s state to force other style updates as well, for example (verified to work for the Valo theme): 

```css
[part="native-checkbox"]:checked ~ [part="checkbox"] {
  opacity: 1;
}
```

**Comment by tomivirkki** [comment]
Would recommend using some property other than `opacity` for the workaround since opacity is something that might be altered by someone extending Valo theme. The “text-field workaround” toggles `backface-visiblity` since it’s less likely to cause side effects.

**Comment by jouni** [comment]
Maybe. I tried backface-visibility, but that didn’t work as good as opacity. Should have tried some others as well, I suppose.

I already pushed the workaround like this to Valo, I don’t think it’s too likely to cause any issues. But we’ll see.

**Comment by web-padawan** [comment]
This hack is now removed on master and I'm not sure if something like this is still needed for Lumo. Closing.
