### ISSUE TITLE
Emojis in checkbox’s text will misalign the text from the checkbox.

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-checkbox#17]
Emojis in checkbox’s text will misalign the text from the checkbox. Pure text works fine. (Safari). Baseline issue

**Comment by jouni** [comment]
Screenshot or didn’t happen 😃

**Comment by tomivirkki** [comment]
![screenshot 2017-08-30 11 00 28](https://user-images.githubusercontent.com/1222264/29861609-7ad03820-8d72-11e7-99bb-3ed4114a609c.png)

**Comment by jouni** [comment]
I don’t think there’s anything we can do about this, this is how Safari renders the text. When you apply a custom line-height, it fixes the issue. So I’m assuming emojis have a different default line height than regular text.

**Comment by tomivirkki** [comment]
Closing as wontfix
