### ISSUE TITLE
Checkbox readonly is not reflected on client side 

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-checkbox#187]
Setting a checkbox as read only by using `setReadOnly(true)` has no impact on the client side DOM. The cb doesn't receive the `readonly` attribute and is therefore clickable. 

(Clickable means, that it reacts visually to the user click, but the state does not change as it is marked as readonly on server side - so it stays checked for instance). 

Setting it disabled by `setEnabled(false)` works as expected.

Discovered in Vaadin 14.0.2

**Comment by web-padawan** [comment]
Closing in favor of #172 as now both issues are in the web component repo so we only keep one open.
