### ISSUE TITLE
Implement HasValidation in CheckBox

### ISSUE THREAD

**Issue by zanonmark** [vaadin/vaadin-checkbox#188]
Vaadin 14.0.0.beta3.

Is it possible to have CheckBox implement the HasValidation interface?

The reason is that all of the major fields (TextField, ComboBox, NumberField, DateField, etc.) implement it, so one can execute .setErrorMessage() on those fields if necessary, which you can't do on CheckBox (only on CheckBoxGroup?!).

Thanks,
MZ

**Comment by web-padawan** [comment]
Now when the issues for Flow components are moved to the web component repos, I'm closing this in favor of #84
