### ISSUE TITLE
CheckboxGroup (flow) `setHelperComponent` doesn't work

### ISSUE THREAD

**Issue by johannest** [vaadin/vaadin-checkbox#191]
### Description
Using CheckboxGroup from Java, `setHelperComponent` doesn't work but `setHelperText` works fine. 
V18.0.0.alpha1

### Expected outcome
When using API  `setHelperComponent` the helper component would be shown below CheckboxGroup

### Actual outcome
Nothing is shown under the checkbox group

### Steps to reproduce
Use bookstore example (https://github.com/vaadin/bookstore-example.git) with V18 alpha, and edit ProductForm adding e.g.:
```category.setHelperComponent(new Label("test-helper foo"));``` The issue is also visible with `Span` as a helper component.

### Browsers Affected (tested with these)
- [X] Chrome
- [X] Firefox
- [X] Edge

**Comment by alvarezguille** [comment]
This issue seems to happen when calling `setItems` after calling `setHelperComponent`.
`setItems` ends up calling `reset` which removes all children including the helper component.
