### ISSUE TITLE
Visual highlight is appearing on disabled checkbox (iOS Safari)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-checkbox#20]
![kapture 2017-08-30 at 11 01 58](https://user-images.githubusercontent.com/1222264/29861682-b3eab5f4-8d72-11e7-84dc-483eab9eaee8.gif)

**Comment by jouni** [comment]
A screenshot/recording would be nice, I don’t understand what highlight you mean.

**Comment by tomivirkki** [comment]
Added screen recording

**Comment by jouni** [comment]
I assume it’s because of a click listener on the wrapper element which is still present even when disabled. An easy fix is to add `-webkit-tap-highlight-color: transparent;` for the disabled state.
