### ISSUE TITLE
Disabled native checkbox missing top border-line

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-checkbox#37]
iOS11 Chrome & Safari

![image](https://user-images.githubusercontent.com/6059356/30695727-34b9cd20-9f14-11e7-8138-f7fdb6ca3df4.png)

**Comment by vicsstar** [comment]
Wrote a sample app that used checkbox in it's disabled state and it displayed correctly in Chrome and Safari on both my phones.
Are there any special/edge cases that determine if it'll happen on any other platform?

**Comment by limonte** [comment]
Still reproducible here: https://cdn.vaadin.com/vaadin-checkbox/1.0.3/demo/#checkbox-basic-demos

iPhone 7 Plus, Safari and Chrome

**Comment by vicsstar** [comment]
Mm, starting to think it's an issue emanating from the demo page. Will investigate further and share what I find.

**Comment by samiheikki** [comment]
Is this still relevant? It is not reproducable with `2.0.0-alpha2`.

**Comment by tomivirkki** [comment]
Please re-open if still relevant
