### ISSUE TITLE
Default look for indeterminate state doesn't work properly in iOS

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-checkbox#38]
iOS Chrome & Safari:

Actual 1: Initially, the indeterminate state looks exactly like the unchecked checkbox.
Expected 1: indeterminate state should be different from checked and unchecked states

Actual 2: After the first tap, the indeterminate checkbox doesn't change its look at all
Expected 2: After the first tap it should be checked

Actual 3: After the second tap, the indeterminate checkbox doesn't change its look at all
Expected 3: After the second tap it should be unchecked

Actual 4: After the third tap, the indeterminate checkbox looks like ugly checked 
![image](https://user-images.githubusercontent.com/6059356/30696567-09f85338-9f17-11e7-8406-c9af9b5279f6.png)
Expected 4: After the third tap it should be checked 
![image](https://user-images.githubusercontent.com/6059356/30696591-2448871c-9f17-11e7-92cf-6a83a3430999.png)

**Comment by tomivirkki** [comment]
iOS doesn't support indeterminate mode https://bugs.webkit.org/show_bug.cgi?id=160484

But this can be handled in a theme like in Valo's case: https://cdn.vaadin.com/vaadin-valo-theme/0.3.1/demo/checkboxes.html

**Comment by vicsstar** [comment]
Does this mean this issue is unresolvable directly and shouldn't be considered unless with the valo theme in place?

**Comment by samiheikki** [comment]
Is this still relevant with `2.0.0-alpha2`?

**Comment by jouni** [comment]
Not relevant anymore. Themes are reaponsible for showing the indeterminate state appropriately.
