### ISSUE TITLE
Non-native default theme

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-checkbox#39]
Because of #38 and the fact that I would like to not expose the native input for styling, we should consider having a non-native default theme, and core styles that hide the native input and layout the checkbox and the label content nicely by default.

**Comment by jouni** [comment]
This is also related to #35

**Comment by jouni** [comment]
These changes require a new major version, as they break the styling API.

**Comment by web-padawan** [comment]
Fixed by #55
