### ISSUE TITLE
Adding the hidden attribute has no effect

### ISSUE THREAD

**Issue by ahie** [vaadin/vaadin-checkbox#41]
Adding the `hidden` attribute to a `vaadin-checkbox` doesn't seem to have any effect. As a user I would expect it to hide the element as if it were a normal input element. See https://jsfiddle.net/ogg9b6tL/ for an example.

**Comment by manolo** [comment]
`hidden` is a browser feature that sets `display=none` when there is no other CSS rule setting display. In this case vaadin-checkbox has the rule `:host {display: inline-block;}`  hence has more priority than default. 
We need to set a rule in all of our elements, already discussed and we will update  them

**Comment by limonte** [comment]
Thanks for reporting @ahie!

Fixed in https://github.com/vaadin/vaadin-checkbox/releases/tag/v1.0.1 and automatically applied to the provided jsfiddle.
