### ISSUE TITLE
Setting the checkbox as indeterminate should clear the checked attribute

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-checkbox#42]
Currently it's possible to set a `vaadin-checkbox` as checked AND indeterminate at the same time.

This leads to some strange behaviors, like clicking on a checkbox which is indeterminate and checked and actually making it unchecked.

In terms of API, when setting the `indeterminate` attribute/property, the `checked` attribute/property should be cleared (or set to `false`).

Example:
When having this:
```html
<vaadin-checkbox id="my-check" checked></vaadin-checkbox>
```
... and setting this:
```javascript
document.getElementById("my-check").indeterminate = true;
```
... we end up with this:
```html
<vaadin-checkbox id="my-check" checked indeterminate></vaadin-checkbox>
```
... and if the user clicks on it we end up with this:
```html
<vaadin-checkbox id="my-check"></vaadin-checkbox>
```

There is a counterpart issue on Flow: https://github.com/vaadin/vaadin-checkbox-flow/issues/6

**Comment by tomivirkki** [comment]
> Currently it's possible to set a vaadin-checkbox as checked AND indeterminate at the same time.
> This leads to some strange behaviors, like clicking on a checkbox which is indeterminate and checked and actually making it unchecked.

This is how native checkbox behaves. Why is it a problem in `<vaadin-checkbox>`s case? This change broke `<vaadin-grid>`s build because its selection column relies on the native behavior of `<vaadin-checkbox>`. If no-one opposes I'd like to revert this change. @jouni  @YuriyVaadin @platosha @gilberto-torrezan?

**Comment by gilberto-torrezan** [comment]
That caused a problem in Flow. If reverted, we will need to implement some hack on top of the webcomponent to clear the `checked` attribute if `indeterminate` is set. it's not a big deal, but that will lead to different behaviors between the pure element and the Flow version.

**Comment by jouni** [comment]
I’m also wondering how will Flow handle native `<input type="checkbox">`?

Although I would like that the element behavior is consistent across all platforms, it could be better for end users that it follows the platform convention instead. So I don’t oppose reverting, if you can get the Flow team on board.

**Comment by web-padawan** [comment]
BTW, this [blog post](https://alexmeub.com/indeterminate-checkboxes/) about the indeterminate state might be useful to understand it better. It also contains comparison of differences across browsers.
