### ISSUE TITLE
Not working with iron-form

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-checkbox#45]
https://jsbin.com/ziqayus/edit?html,console,output

`vaadin-checkbox` shows the same value with `iron-form`'s `serializeForm()` output regardless of whether it is `checked` or not.

**Comment by moderndeveloperllc** [comment]
@manolo, @tomivirkki There appears to be a regression after you added this patch. Check out the JSBin at 

https://jsbin.com/ziqayus/edit?html,console,output

Now the checkboxes are not serialized at all.

**Comment by tomivirkki** [comment]
Ouch, we'll take a look

**Comment by tomivirkki** [comment]
Fix pending in https://github.com/vaadin/vaadin-checkbox/pull/51
