### ISSUE TITLE
Checkbox doesn't work on iPhone

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-checkbox#5]
Can't click any checkbox, live demo: http://flow.app.fi/demo-flow-components-0.1.16-SNAPSHOT/vaadin-checkbox

**Comment by samiheikki** [comment]
https://github.com/vaadin/vaadin-checkbox/blob/master/vaadin-checkbox.html#L178 Removing that allows to click on checkbox on iOS (but doesn't fix clicking the label).
