### ISSUE TITLE
Checkbox with no label content is too wide

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-checkbox#69]
It seems the `:empty` pseudo class does not work for the label part, as it always contains the `<slot>` element: https://github.com/vaadin/vaadin-checkbox/blob/master/theme/lumo/vaadin-checkbox.html#L27-L29

The result is that a plain checkbox (for example the selection checkboxes inside vaadin-grid) take more space than needed.

**Comment by web-padawan** [comment]
Here is the actual line location: https://github.com/vaadin/vaadin-checkbox/blob/a7daade7fa1ef349df5f4ea0f3ec9eee0e14a1b2/theme/lumo/vaadin-checkbox-styles.html#L28
