### ISSUE TITLE
Executing click() on the element does not correctly toggle the state when indeterminate=true

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-checkbox#70]
The problem can be seen here: https://cdn.vaadin.com/vaadin-checkbox/2.0.0-alpha7/demo/#checkbox-indeterminate-demos

If you click the "Select all" checkbox, it moves from `indeterminate` state to `checked` state.
If you instead find the element in the inspector and call `$0.click();`, it moves from `indeterminate` state to `unchecked` state.

A workaround seems to be to call `click();` on the native input element, but you can't easily get a reference to that

**Comment by web-padawan** [comment]
Introduced by the workaround for IE and Edge implemented here: https://github.com/vaadin/vaadin-checkbox/blob/master/src/vaadin-checkbox.html#L255

I took a quick look and it seems that we should also call `_toggleChecked ` in that block for consistency. @tomivirkki WDYT?
