### ISSUE TITLE
Native outline appears around the select checkbox on double-click

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-checkbox#71]
Chrome/Linux, mouse double-click:

![peek 2018-02-21 15-20](https://user-images.githubusercontent.com/6059356/36482160-feeca4cc-171a-11e8-90a3-3971d00c7215.gif)

@jouni I believe `outline: none` should help. Should that be in core styles or in a theme? IMO it should be in core styles since we have the replacement for handling the focus - control-state-mixin.

**Comment by web-padawan** [comment]
Fixed in 51dc7b5
